[package]
name = "albion-translator"
version = "0.1.0"
edition = "2024"

[dependencies]
albion-network-lib = { path = "../albion-network-lib" }
anyhow = "1.0"
chrono = "0.4.44"
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
pcap = "2.2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
